import csv
import sqlite3
from pathlib import Path

DB_PATH = Path("autoverso.db")
CSV_PATH = Path("prime_20_auto.csv")

cars = [
    {
        "name": "Mini Cooper 1.5 136 CV",
        "brand": "Mini",
        "model": "Cooper",
        "version": "1.5 136 CV",
        "years": "2014-oggi",
        "fuel": "Benzina",
        "car_type": "Compatta premium",
        "power": 136,
        "torque": 220,
        "consumption": 5.5,
        "zero100": 7.9,
        "speed_max": 210,
        "price_min": 12000,
        "price_max": 22000,
        "reliability": 8,
        "comfort": 7,
        "fun": 9,
        "pros": "Bella, agile, divertente, interni curati, immagine premium.",
        "cons": "Spazio posteriore limitato, bagagliaio piccolo, costi non bassissimi.",
        "ideal": "Citta, uso quotidiano e guida divertente.",
        "checks": "Tagliandi, frizione, cambio, sospensioni, elettronica, gomme.",
        "mods": "Molle sportive moderate, cerchi leggeri, gomme di qualita, scarico omologato.",
        "avoid": "Assetto troppo basso, scarico non omologato, mappa aggressiva.",
        "verdict": "Ottima scelta se vuoi una compatta bella, premium e divertente."
    },
    {
        "name": "Fiat Punto 1.3 Multijet",
        "brand": "Fiat",
        "model": "Punto",
        "version": "1.3 Multijet",
        "years": "2003-2018",
        "fuel": "Diesel",
        "car_type": "Utilitaria",
        "power": 95,
        "torque": 200,
        "consumption": 4.2,
        "zero100": 11.7,
        "speed_max": 178,
        "price_min": 2500,
        "price_max": 7500,
        "reliability": 8,
        "comfort": 6,
        "fun": 5,
        "pros": "Consuma poco, ricambi economici, motore molto diffuso.",
        "cons": "Interni semplici, prestazioni tranquille, attenzione a EGR e manutenzione.",
        "ideal": "Casa-lavoro, uso quotidiano economico e lunghi tragitti.",
        "checks": "Km reali, tagliandi, distribuzione, frizione, turbina, EGR, fumo allo scarico.",
        "mods": "Manutenzione completa, gomme buone, freni in ordine, cerchi sobri.",
        "avoid": "Eliminazione FAP, scarico non omologato, rimappa pesante, assetto estremo.",
        "verdict": "Scelta intelligente se vuoi spendere poco e consumare poco."
    },
    {
        "name": "Volkswagen Golf GTI 2.0 TSI",
        "brand": "Volkswagen",
        "model": "Golf",
        "version": "GTI 2.0 TSI",
        "years": "2013-2020",
        "fuel": "Benzina",
        "car_type": "Compatta sportiva",
        "power": 230,
        "torque": 350,
        "consumption": 7.5,
        "zero100": 6.4,
        "speed_max": 248,
        "price_min": 18000,
        "price_max": 32000,
        "reliability": 7,
        "comfort": 8,
        "fun": 9,
        "pros": "Veloce, equilibrata, comoda, qualita alta.",
        "cons": "Costo alto, manutenzione piu cara, attenzione a DSG e tagliandi.",
        "ideal": "Sportiva quotidiana, viaggi, guida brillante.",
        "checks": "Storico tagliandi, cambio DSG, turbina, freni, gomme, modifiche precedenti.",
        "mods": "Gomme sportive, freni migliori, assetto di qualita, scarico omologato.",
        "avoid": "Mappa senza controlli, preparazioni economiche, assetto estremo.",
        "verdict": "Una delle migliori compatte sportive per equilibrio generale."
    },
    {
        "name": "Toyota Yaris Hybrid",
        "brand": "Toyota",
        "model": "Yaris",
        "version": "Hybrid",
        "years": "2012-oggi",
        "fuel": "Ibrida benzina",
        "car_type": "Utilitaria ibrida",
        "power": 116,
        "torque": 120,
        "consumption": 3.8,
        "zero100": 9.7,
        "speed_max": 175,
        "price_min": 11000,
        "price_max": 24000,
        "reliability": 9,
        "comfort": 7,
        "fun": 6,
        "pros": "Affidabile, consuma poco, ottima in citta.",
        "cons": "Poco sportiva, bagagliaio medio, sound poco emozionante.",
        "ideal": "Citta, neopatentati, bassi consumi, affidabilita.",
        "checks": "Tagliandi, batteria ibrida, freni, gomme, stato carrozzeria.",
        "mods": "Gomme efficienti, manutenzione ufficiale, estetica leggera.",
        "avoid": "Scarico sportivo, assetto estremo, modifiche meccaniche pesanti.",
        "verdict": "Perfetta se cerchi risparmio, affidabilita e praticita."
    },
    {
        "name": "Fiat 500 Abarth",
        "brand": "Fiat",
        "model": "500 Abarth",
        "version": "Abarth",
        "years": "2008-oggi",
        "fuel": "Benzina",
        "car_type": "Piccola sportiva",
        "power": 145,
        "torque": 206,
        "consumption": 6.5,
        "zero100": 7.8,
        "speed_max": 210,
        "price_min": 13000,
        "price_max": 25000,
        "reliability": 7,
        "comfort": 5,
        "fun": 9,
        "pros": "Divertente, sound piacevole, estetica forte.",
        "cons": "Rigida, poco spaziosa, costi superiori a una 500 normale.",
        "ideal": "Divertimento, citta, appassionati.",
        "checks": "Modifiche precedenti, frizione, turbina, freni, assetto, gomme.",
        "mods": "Scarico omologato, gomme sportive, freni migliori, assetto di qualita.",
        "avoid": "Scarichi non omologati, assetti troppo rigidi, mappe spinte senza controlli.",
        "verdict": "Auto emozionale, perfetta se vuoi divertirti."
    },
    {
        "name": "Fiat Panda 1.2",
        "brand": "Fiat",
        "model": "Panda",
        "version": "1.2",
        "years": "2012-oggi",
        "fuel": "Benzina",
        "car_type": "City car",
        "power": 69,
        "torque": 102,
        "consumption": 5.2,
        "zero100": 14.2,
        "speed_max": 164,
        "price_min": 5000,
        "price_max": 12000,
        "reliability": 8,
        "comfort": 6,
        "fun": 4,
        "pros": "Economica, semplice, pratica, ricambi facili.",
        "cons": "Prestazioni basse, interni semplici, poco adatta a guida sportiva.",
        "ideal": "Citta, neopatentati, uso quotidiano economico.",
        "checks": "Frizione, tagliandi, sospensioni, gomme, piccoli urti cittadini.",
        "mods": "Gomme buone, manutenzione, autoradio, estetica leggera.",
        "avoid": "Assetto rigido, scarico sportivo, modifiche meccaniche inutili.",
        "verdict": "Scelta molto razionale se vuoi spendere poco."
    },
    {
        "name": "Fiat 500 1.2",
        "brand": "Fiat",
        "model": "500",
        "version": "1.2",
        "years": "2007-oggi",
        "fuel": "Benzina",
        "car_type": "City car",
        "power": 69,
        "torque": 102,
        "consumption": 5.1,
        "zero100": 12.9,
        "speed_max": 160,
        "price_min": 6000,
        "price_max": 14000,
        "reliability": 7,
        "comfort": 6,
        "fun": 5,
        "pros": "Bella, compatta, facile da parcheggiare, molto diffusa.",
        "cons": "Spazio limitato, prezzo usato spesso alto, prestazioni tranquille.",
        "ideal": "Citta, neopatentati, uso urbano.",
        "checks": "Tagliandi, frizione, sospensioni, carrozzeria, gomme.",
        "mods": "Cerchi sobri, gomme buone, interni, detailing.",
        "avoid": "Assetto troppo basso, scarichi rumorosi, cerchi troppo grandi.",
        "verdict": "Ottima se vuoi una city car bella e facile."
    },
    {
        "name": "Lancia Ypsilon 1.2",
        "brand": "Lancia",
        "model": "Ypsilon",
        "version": "1.2",
        "years": "2011-oggi",
        "fuel": "Benzina",
        "car_type": "Utilitaria",
        "power": 69,
        "torque": 102,
        "consumption": 5.3,
        "zero100": 14.5,
        "speed_max": 163,
        "price_min": 5000,
        "price_max": 13000,
        "reliability": 7,
        "comfort": 7,
        "fun": 4,
        "pros": "Comoda, elegante, facile da usare, costi contenuti.",
        "cons": "Prestazioni basse, guida poco sportiva, dotazioni variabili.",
        "ideal": "Citta, neopatentati, uso quotidiano tranquillo.",
        "checks": "Tagliandi, frizione, interni, elettronica, gomme.",
        "mods": "Estetica leggera, gomme buone, manutenzione ordinata.",
        "avoid": "Tuning pesante, scarico sportivo, assetto estremo.",
        "verdict": "Buona utilitaria elegante e semplice."
    },
    {
        "name": "Volkswagen Polo 1.0 TSI",
        "brand": "Volkswagen",
        "model": "Polo",
        "version": "1.0 TSI",
        "years": "2017-oggi",
        "fuel": "Benzina",
        "car_type": "Utilitaria premium",
        "power": 95,
        "torque": 175,
        "consumption": 5.0,
        "zero100": 10.8,
        "speed_max": 187,
        "price_min": 12000,
        "price_max": 22000,
        "reliability": 8,
        "comfort": 8,
        "fun": 6,
        "pros": "Qualita buona, consumi bassi, motore brillante.",
        "cons": "Prezzo usato alto, manutenzione piu cara di utilitarie economiche.",
        "ideal": "Uso quotidiano, citta, autostrada leggera.",
        "checks": "Tagliandi, cambio, frizione, elettronica, gomme.",
        "mods": "Cerchi omologati, gomme buone, assetto moderato.",
        "avoid": "Mappe spinte, assetto troppo rigido, scarico non omologato.",
        "verdict": "Utilitaria completa e matura."
    },
    {
        "name": "Audi A1 1.4 TFSI",
        "brand": "Audi",
        "model": "A1",
        "version": "1.4 TFSI",
        "years": "2010-2018",
        "fuel": "Benzina",
        "car_type": "Compatta premium",
        "power": 122,
        "torque": 200,
        "consumption": 5.8,
        "zero100": 8.9,
        "speed_max": 203,
        "price_min": 8000,
        "price_max": 17000,
        "reliability": 7,
        "comfort": 8,
        "fun": 7,
        "pros": "Qualita interna, immagine premium, motore piacevole.",
        "cons": "Spazio limitato, prezzi usato non bassi, manutenzione premium.",
        "ideal": "Citta, uso quotidiano, chi vuole una piccola premium.",
        "checks": "Tagliandi, cambio, catena/cinghia secondo versione, elettronica, gomme.",
        "mods": "Cerchi leggeri, gomme buone, assetto moderato.",
        "avoid": "Mappa aggressiva, scarico non omologato, assetto troppo basso.",
        "verdict": "Buona alternativa premium a Mini e Polo."
    },
    {
        "name": "Audi A3 2.0 TDI",
        "brand": "Audi",
        "model": "A3",
        "version": "2.0 TDI",
        "years": "2012-2020",
        "fuel": "Diesel",
        "car_type": "Compatta premium",
        "power": 150,
        "torque": 340,
        "consumption": 4.7,
        "zero100": 8.4,
        "speed_max": 216,
        "price_min": 13000,
        "price_max": 26000,
        "reliability": 8,
        "comfort": 8,
        "fun": 7,
        "pros": "Ottima per viaggi, consumi bassi, qualita alta.",
        "cons": "Costi manutenzione superiori, attenzione a chilometri reali e uso precedente.",
        "ideal": "Autostrada, viaggi, uso quotidiano premium.",
        "checks": "Km reali, tagliandi, DPF, EGR, frizione/DSG, turbina.",
        "mods": "Gomme di qualita, freni buoni, manutenzione, estetica sobria.",
        "avoid": "Eliminazione DPF, mappe aggressive, assetto estremo.",
        "verdict": "Molto valida se fai tanti chilometri."
    },
    {
        "name": "BMW Serie 1 118d",
        "brand": "BMW",
        "model": "Serie 1",
        "version": "118d",
        "years": "2011-2019",
        "fuel": "Diesel",
        "car_type": "Compatta premium",
        "power": 143,
        "torque": 320,
        "consumption": 4.8,
        "zero100": 8.9,
        "speed_max": 212,
        "price_min": 10000,
        "price_max": 23000,
        "reliability": 7,
        "comfort": 7,
        "fun": 8,
        "pros": "Guida piacevole, immagine premium, consumi buoni.",
        "cons": "Manutenzione non economica, attenzione a catena e storico tagliandi.",
        "ideal": "Uso quotidiano, viaggi, chi cerca guida piu sportiva.",
        "checks": "Catena distribuzione, tagliandi, frizione, turbina, gomme, assetto.",
        "mods": "Gomme buone, freni, assetto di qualita, estetica M-style sobria.",
        "avoid": "Mappe spinte, assetto economico, auto molto chilometrate senza storico.",
        "verdict": "Interessante se vuoi una compatta premium divertente."
    },
    {
        "name": "Mercedes Classe A 180d",
        "brand": "Mercedes",
        "model": "Classe A",
        "version": "180d",
        "years": "2012-2018",
        "fuel": "Diesel",
        "car_type": "Compatta premium",
        "power": 109,
        "torque": 260,
        "consumption": 4.3,
        "zero100": 11.3,
        "speed_max": 190,
        "price_min": 12000,
        "price_max": 24000,
        "reliability": 8,
        "comfort": 8,
        "fun": 6,
        "pros": "Immagine premium, consumi bassi, buona qualita.",
        "cons": "Prestazioni tranquille, prezzi usato alti, manutenzione premium.",
        "ideal": "Uso quotidiano, viaggi, consumi bassi.",
        "checks": "Tagliandi, cambio, frizione, DPF, elettronica, gomme.",
        "mods": "Cerchi omologati, gomme buone, estetica AMG sobria.",
        "avoid": "Rimappe aggressive, scarichi non omologati, assetti troppo bassi.",
        "verdict": "Compatta premium razionale e parca."
    },
    {
        "name": "Ford Fiesta 1.0 EcoBoost",
        "brand": "Ford",
        "model": "Fiesta",
        "version": "1.0 EcoBoost",
        "years": "2013-2023",
        "fuel": "Benzina",
        "car_type": "Utilitaria",
        "power": 100,
        "torque": 170,
        "consumption": 5.2,
        "zero100": 10.8,
        "speed_max": 180,
        "price_min": 7000,
        "price_max": 17000,
        "reliability": 7,
        "comfort": 7,
        "fun": 8,
        "pros": "Guida piacevole, motore brillante, costi abbastanza gestibili.",
        "cons": "Controllare manutenzione, cinghia secondo versione, uso precedente.",
        "ideal": "Citta, extraurbano, chi vuole utilitaria divertente.",
        "checks": "Tagliandi, cinghia, frizione, turbo, gomme, freni.",
        "mods": "Gomme buone, assetto moderato, freni, estetica ST-line.",
        "avoid": "Mappa pesante, manutenzione saltata, assetto economico.",
        "verdict": "Una delle utilitarie piu piacevoli da guidare."
    },
    {
        "name": "Renault Clio 1.5 dCi",
        "brand": "Renault",
        "model": "Clio",
        "version": "1.5 dCi",
        "years": "2012-2019",
        "fuel": "Diesel",
        "car_type": "Utilitaria",
        "power": 90,
        "torque": 220,
        "consumption": 4.0,
        "zero100": 12.0,
        "speed_max": 180,
        "price_min": 6000,
        "price_max": 14000,
        "reliability": 8,
        "comfort": 7,
        "fun": 5,
        "pros": "Consumi bassi, comoda, buona per tanti km.",
        "cons": "Prestazioni tranquille, attenzione a manutenzione diesel.",
        "ideal": "Viaggi economici, casa-lavoro, extraurbano.",
        "checks": "Tagliandi, DPF, EGR, frizione, turbina, km reali.",
        "mods": "Manutenzione, gomme buone, freni in ordine.",
        "avoid": "Eliminazione DPF, rimappa pesante, scarico rumoroso.",
        "verdict": "Diesel piccolo molto sensato se fai strada."
    },
    {
        "name": "Peugeot 208 1.2 PureTech",
        "brand": "Peugeot",
        "model": "208",
        "version": "1.2 PureTech",
        "years": "2012-oggi",
        "fuel": "Benzina",
        "car_type": "Utilitaria",
        "power": 82,
        "torque": 118,
        "consumption": 5.0,
        "zero100": 12.2,
        "speed_max": 175,
        "price_min": 7000,
        "price_max": 18000,
        "reliability": 7,
        "comfort": 7,
        "fun": 6,
        "pros": "Bella, comoda, consumi contenuti, interni moderni.",
        "cons": "Prestazioni tranquille, controllare manutenzione motore.",
        "ideal": "Citta, neopatentati, uso quotidiano.",
        "checks": "Tagliandi, cinghia secondo versione, elettronica, gomme.",
        "mods": "Cerchi omologati, gomme buone, estetica leggera.",
        "avoid": "Assetto troppo rigido, scarico sportivo inutile, manutenzione saltata.",
        "verdict": "Utilitaria moderna e gradevole."
    },
    {
        "name": "Alfa Romeo MiTo 1.4 Turbo",
        "brand": "Alfa Romeo",
        "model": "MiTo",
        "version": "1.4 Turbo",
        "years": "2008-2018",
        "fuel": "Benzina",
        "car_type": "Compatta sportiva",
        "power": 155,
        "torque": 230,
        "consumption": 6.5,
        "zero100": 8.0,
        "speed_max": 215,
        "price_min": 6000,
        "price_max": 14000,
        "reliability": 7,
        "comfort": 6,
        "fun": 8,
        "pros": "Linea particolare, motore brillante, guida sfiziosa.",
        "cons": "Interni datati, attenzione a manutenzione e auto modificate.",
        "ideal": "Giovani appassionati, uso quotidiano sportivo.",
        "checks": "Tagliandi, turbina, frizione, sospensioni, elettronica, modifiche.",
        "mods": "Assetto moderato, gomme buone, freni, scarico omologato.",
        "avoid": "Mappe aggressive, assetto estremo, esemplari maltrattati.",
        "verdict": "Scelta interessante per chi vuole una piccola sportiva italiana."
    },
    {
        "name": "Jeep Renegade 1.6 Multijet",
        "brand": "Jeep",
        "model": "Renegade",
        "version": "1.6 Multijet",
        "years": "2014-oggi",
        "fuel": "Diesel",
        "car_type": "SUV compatto",
        "power": 120,
        "torque": 320,
        "consumption": 5.2,
        "zero100": 10.2,
        "speed_max": 178,
        "price_min": 12000,
        "price_max": 25000,
        "reliability": 7,
        "comfort": 7,
        "fun": 5,
        "pros": "Posizione alta, stile personale, buona praticita.",
        "cons": "Consumi superiori a utilitaria, peso, costi gomme.",
        "ideal": "Famiglia piccola, citta, viaggi tranquilli.",
        "checks": "Tagliandi, DPF, EGR, frizione, gomme, sospensioni.",
        "mods": "Gomme buone, manutenzione, estetica sobria.",
        "avoid": "Rimappe pesanti, cerchi enormi, assetto inutile.",
        "verdict": "SUV compatto valido se vuoi posizione alta e praticita."
    },
    {
        "name": "Nissan Qashqai 1.5 dCi",
        "brand": "Nissan",
        "model": "Qashqai",
        "version": "1.5 dCi",
        "years": "2014-2021",
        "fuel": "Diesel",
        "car_type": "SUV compatto",
        "power": 110,
        "torque": 260,
        "consumption": 4.5,
        "zero100": 11.9,
        "speed_max": 182,
        "price_min": 11000,
        "price_max": 23000,
        "reliability": 8,
        "comfort": 8,
        "fun": 5,
        "pros": "Comodo, spazioso, consumi bassi, molto diffuso.",
        "cons": "Poco sportivo, attenzione a diesel usati male in citta.",
        "ideal": "Famiglia, viaggi, uso quotidiano.",
        "checks": "DPF, EGR, tagliandi, frizione, gomme, km reali.",
        "mods": "Gomme buone, manutenzione, accessori pratici.",
        "avoid": "Eliminazione DPF, rimappe pesanti, assetto sportivo.",
        "verdict": "SUV razionale e molto sfruttabile."
    },
    {
        "name": "Opel Corsa 1.2",
        "brand": "Opel",
        "model": "Corsa",
        "version": "1.2",
        "years": "2014-oggi",
        "fuel": "Benzina",
        "car_type": "Utilitaria",
        "power": 75,
        "torque": 118,
        "consumption": 5.2,
        "zero100": 13.2,
        "speed_max": 170,
        "price_min": 6000,
        "price_max": 15000,
        "reliability": 7,
        "comfort": 7,
        "fun": 5,
        "pros": "Semplice, comoda, costi gestibili.",
        "cons": "Prestazioni tranquille, meno emozionale di alcune rivali.",
        "ideal": "Citta, neopatentati, uso quotidiano.",
        "checks": "Tagliandi, frizione, elettronica, sospensioni, gomme.",
        "mods": "Manutenzione, gomme buone, estetica leggera.",
        "avoid": "Tuning pesante, assetto estremo, modifiche economiche.",
        "verdict": "Utilitaria concreta e facile da gestire."
    },
    {
        "name": "Volkswagen Golf 1.6 TDI",
        "brand": "Volkswagen",
        "model": "Golf",
        "version": "1.6 TDI",
        "years": "2012-2020",
        "fuel": "Diesel",
        "car_type": "Compatta",
        "power": 105,
        "torque": 250,
        "consumption": 4.2,
        "zero100": 10.7,
        "speed_max": 195,
        "price_min": 9000,
        "price_max": 20000,
        "reliability": 8,
        "comfort": 8,
        "fun": 6,
        "pros": "Equilibrata, consumi bassi, buona qualita.",
        "cons": "Prezzi usato alti, attenzione a DPF e chilometri reali.",
        "ideal": "Uso quotidiano, viaggi, autostrada.",
        "checks": "Km reali, tagliandi, DPF, EGR, frizione/DSG, gomme.",
        "mods": "Gomme buone, freni, manutenzione, estetica sobria.",
        "avoid": "Eliminazione DPF, mappe spinte, assetti estremi.",
        "verdict": "Compatta diesel molto razionale."
    }
]

columns = [
    "name", "brand", "model", "version", "years", "fuel", "car_type",
    "power", "torque", "consumption", "zero100", "speed_max",
    "price_min", "price_max", "reliability", "comfort", "fun",
    "pros", "cons", "ideal", "checks", "mods", "avoid", "verdict"
]

with CSV_PATH.open("w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=columns)
    writer.writeheader()
    writer.writerows(cars)

connection = sqlite3.connect(DB_PATH)
connection.row_factory = sqlite3.Row
cur = connection.cursor()

inserted = 0
skipped = 0

for car in cars:
    existing = cur.execute("SELECT id FROM cars WHERE lower(name) = lower(?)", (car["name"],)).fetchone()

    if existing:
        skipped += 1
        continue

    cur.execute("""
        INSERT INTO cars (
            name, brand, model, version, years, fuel, car_type, power, torque,
            consumption, zero100, speed_max, price_min, price_max, reliability,
            comfort, fun, pros, cons, ideal, checks, mods, avoid, verdict
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        car["name"], car["brand"], car["model"], car["version"], car["years"],
        car["fuel"], car["car_type"], car["power"], car["torque"],
        car["consumption"], car["zero100"], car["speed_max"],
        car["price_min"], car["price_max"], car["reliability"],
        car["comfort"], car["fun"], car["pros"], car["cons"], car["ideal"],
        car["checks"], car["mods"], car["avoid"], car["verdict"]
    ))

    inserted += 1

connection.commit()
connection.close()

print("CSV creato:", CSV_PATH)
print("Auto nuove inserite:", inserted)
print("Auto gia presenti saltate:", skipped)
print("Totale obiettivo: circa 20 auto nel database")
